[supabase]
url = "https://txdnygcbcuxifgfixrdp.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4ZG55Z2NiY3V4aWZnZml4cmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzYwODgsImV4cCI6MjA3MjgxMjA4OH0.MuDJOvV6EnPrU71NsgcMO1S1RUvmdOvGwxpCFqAqjBU"
